Advantages and disadvantages in the workforce
mms142-groupd-2023/mms142-groupd-2023.github.io pull request #21
Opened 2023-12-12 10:54 UTC by certezayenny

2023-12-12 11:29 UTC, DaveClemente requested changes
<img src="files/images/Coca-Cola-canning-line.jpg" alt="Canning Line" class="flex-item">

hindi nag rerender yung image for canning, maybe need ng space: Coca-Cola canning line.jpg (if it would not be bother, pwede pa ulit pag snip nung image? either wala yung black border or may border on all sides)

can you also add a space after "source:"
<img width="159" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/e07e3ce8-a5dd-4f53-91d3-2b9ea20f030f">

2023-12-12 11:35 UTC, DaveClemente requested changes
Also, can you remove some of the br tags, it seems off 

<img width="554" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/f4839699-55db-446f-9e7f-ed8a03c41603">

<img width="577" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/29b082c2-8e15-4b10-bbf8-426b22acb723">

but can you add one br tag here before the references to 

<img width="523" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/a5463cc4-7c64-4e15-8d07-fca0cfca822c">

2023-12-12 11:57 UTC, DaveClemente requested changes
sorry, di ko pala na consider yung website look kanina:

- [ ] Make a space in "Source:_Link"
- [ ] Make a square (bg color #EFEFEF) for the end paragraph in advantages same goes sa first paragraph ng disadvantage (you can refer sa gawa ni marga sa branch nila, well same lang pala un nung sa bg nung advantages ibahin lang color but kung kaya mo hindi siya full width yung color similar sa image below oks din :))

<img width="453" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/19f300ec-79ab-41c1-a905-a05b3d9faeef">

- [ ] Also try mo i-format yung image beside the text like this if you can: 
<img width="408" alt="image" src="https://github.com/mms142-groupd-2023/mms142-groupd-2023.github.io/assets/150673958/3fcba578-2722-4db2-a99d-8071f419c445">

2023-12-13 08:30 UTC, DaveClemente approved these changes

2023-12-14 08:33 UTC, DaveClemente approved these changes

2023-12-14 10:06 UTC, hcora approved these changes

2023-12-14 10:07 UTC, DaveClemente approved these changes

2023-12-14 10:07 UTC, MargaCatalan approved these changes

2023-12-14 10:12 UTC, merged